jirka-h/haveged

src/haveged.c
With this there should be a more significant message if the address is already in use
Signed-off-by: Werner Fink <werner@suse.de>
=> Avoid misleading message if cmd socket is in use

src/havegecollect.c
This change resolves #9 by fixing the variable that haveged checks during the rng warmup. Previously it was checking `hctxt->havege_tic` but `h_ctxt->havege_tics[i>>3]` is what actually gets updated when in diagnostics mode. `HTICK1` correctly references the right variable in both modes.
Testing was done by checking an output can be obtained:
```
> src/haveged -r 2 -n 100
havege_diagnostic: listening socket at 3
Writing 100  output to sample
```
=> Fix haveged diagnostics capture mode

nist/packtest.c
Those tests takes enough time on mips to outbound the allowed 5 minutes of inactivity.
So let's output a little more progress messages as a workaround.
=> Output some progress during CUSUM and RANDOM EXCURSION test

src/havegecollect.h
The current implementation simply fail to build (on Itanium) and the `cpuid` instruction on Itanium spreads out value differently than what 'cpuid' does on i386 and amd64, so the code would need to be worked out quite differently to work.
In the meantime, disabling CPUID support will make haveged use the default cache values on ia64.
=> Remove support for CPUID on ia64

NEWS
1. Restore missing release v1.9.1
2. Fix release date for v1.9.2
3. Remove extraneous whitespace
(1) and (2) are from a Debian patch I'm including in `haveged/1.9.4-1` (upload pending, should hit `sid` today)
=> Fixup the changelog

src/haveged.c
Make max_bits signed so that error checking works.
=> Fix type mismatch in get_poolsize

init.d/service.redhat
Update PIDFile to fix the following message during the boot sequence:
"PIDFile= references path below legacy directory /var/run/, updating /var/run/haveged.pid → /run/haveged.pid;
please update the unit file accordingly."
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
=> service.redhat: update PIDFile

init.d/Makefile.am
install-data-hook should depend on install-exec-hook, or the
haveged.service might be installed incorrectly when build
with -j option.
Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> init.d/Makefile.am: add missing dependency

src/havegetune.c
Some ARM cpus does not report the cache size or say it is -1 in sysfs.
It has been observed on xgene and thunderx machines.
Fall back to the generic cache size when that happens so we don't
segfault.
Should fix https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866306
=> Fix segfault on arm machines

src/havege.c
Happens like 1/20 tries on x86_32 linux otherwise
=> fix segv at start

src/havegetune.c
Previously failed with:
```
havegetune.c:190:12: error: ‘BUILD_THREAD’ undeclared (first use in this function); did you mean ‘BUILD_THREADS’?
190 |    *bp++ = BUILD_THREAD;
|            ^~~~~~~~~~~~
|            BUILD_THREADS
```
Signed-off-by: Lars Wendler <polynomial-c@gentoo.org>
=> build: Fix compilation with --enable-threads

configure, configure.ac
Avoid errors when `/bin/sh` is not bash(1).
=> Use POSIX shell comparison for equality

src/havege.c, src/havege.h, src/haveged.c
The bug happens when havege is built with --enable-threads.
On shutdown the following crash happens:
```
3109      p = mem2chunk (mem);
(gdb) bt
#0  __GI___libc_free (mem=0x7f630c066000) at malloc.c:3109
#1  0x00007f630c035f9e in havege_destroy (hptr=0x564b56b6b900) at havege.c:197
#2  0x0000564b561c3dca in error_exit (format=<optimized out>) at haveged.c:708
#3  0x0000564b561c33f1 in run_daemon (argv=0x7ffce7627758, path=0x564b56b6b2a0
```
valgrind helped me to understand it was a mmap() / free()
mismatch:
```
For lists of detected and suppressed errors, rerun with: -s
ERROR SUMMARY: 14 errors from 2 contexts (suppressed: 0 from 0)
Invalid free() / delete / delete[] / realloc()
at 0x48389CB: free (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
by 0x48AED9F: havege_destroy …
```
=> haveged: fix crash on shutdown in threaded mode

src/havegecmd.h
Avoids these errors:
havegecmd.c: In function ‘cmd_listen’:
havegecmd.c:105: error: ‘SOCK_CLOEXEC’ undeclared (first use in this function)
havegecmd.c:105: error: (Each undeclared identifier is reported only once
havegecmd.c:105: error: for each function it appears in.)
havegecmd.c:105: error: ‘SOCK_NONBLOCK’ undeclared (first use in this function)
havegecmd.c: In function ‘cmd_connect’:
havegecmd.c:154: error: ‘SOCK_CLOEXEC’ undeclared (first use in this function)
havegecmd.c:154: error: ‘SOCK_NONBLOCK’ undeclared (first use in this function)
=> don't use SOCK_CLOEXEC or SOCK_NONBLOCK if not available

init.d/service.fedora
All changes were applied to `init.d/service.fedora`; I shipped them moments
ago in Debian “sid” (a.k.a. unstable) as `haveged/1.9.8-3`.
of other services.
(namespaces, personalities, realtime scheduling)
=> haveged.service: Tighten-down security settings

src/haveged.c
We won't have access to change the watermark if we're running in
an unprivileged container, so if the error is EACCES just warn
and continue
=> don't fail completely if we can't set write wakeup watermark

src/havegecmd.c, src/haveged.c, src/haveged.h
- bind failure should be fatal
- error sending on socket should be non-fatal
- return chroot error
Signed-off-by: Michal Suchanek <msuchanek@suse.de>
=> havegecmd: Fix error handling.

config.h.in, configure.ac, src/haveged.c
Check for HAVE_GETAUXVAL or HAVE_SYS_AUXV_H before using
getauxval to avoid a build failure on uclibc
Fixes:
/bin/bash ../libtool  --tag=CC   --mode=compile /home/pjtexier/Bureau/buildroot/pj/bootlin-armv5-uclibc/host/bin/arm-linux-gcc -DHAVE_CONFIG_H -I. -I..   -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wextra -Wpedantic -I.. -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os   -c -o libhavege_la-havege.lo `test -f 'havege.c' || echo './'`havege.c
/bin/bash ../libtool  --tag=CC   --mode=compile /home/pjtexier/Bureau/buildroot/pj/bootlin-armv5-uclibc/host/bin/arm-linux-gcc -DHAVE_CONFIG_H -I. -I..   -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wextra -Wpedantic -I.. -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE …
=> haveged: fix build on uclibc

src/haveged.c
Rather than rounding bits down, round them up. Otherwise 249 bits full in a 256 bit pool won't ever get filled up with the additional 7 bits. In addition, target a full pool rather than a half pool, since a full pool is sometimes required.
CC @jmberg
=> Round bits up and target full pool size

README.md
The haveged-like jitter entropy algo was added in 5.4. The 5.6 commit is
for making /dev/random never block. I kept the reference to the latter
in there too, in case it's relevant, but I'm pretty sure what you had in
mind here was the 5.4 commit.
=> Specify right kernel commit in README

configure.ac, src/havegecmd.c, src/havegecmd.h, src/haveged.c
We found that with some system configurations zypper and lsof were complaining about haveged using deleted file (haveged binary itself) after each reboot of the system. On kernels =< 5.6 haveged is started early in the initramfs. Before switching to the permanent rootfs, haveged was supposed to do a chdir to `/sysroot` and re-executes the haveged binary from `/sysroot`. This is supposed to be done by the `haveged-switch-root` service.
The `haveged-switch-service` failed due to a communication problem. There are 2 haveged instances running on the system when the `haveged-switch-service` is started - one haveged daemon instance and one switch instances telling the daemon to switch its root directory.
The two daemons communicate via abstract namespace unix socket. Depending on the scheduling …
=> Synchronize haveged instances during switch root

contrib/Fedora/90-haveged.rules, contrib/SUSE/90-haveged.rules
Fix the following warnings reported by udevadm verify:
```
contrib/Fedora/90-haveged.rules:4 Stray whitespace before comma.
contrib/SUSE/90-haveged.rules:4 Stray whitespace before comma.
```
=> 90-haveged.rules: fix warnings reported by udevadm verify

src/haveged.c
Hi,
when /dev/shm doesn't exist, haveged fails to start because it can't create its semaphore. I've applied this in Debian some time ago and it would be nice if you could merge it.
Regards,
Daniel
=> Creating /dev/shm if its not existing, otherwise haveged fails to start.
